using US.SharedKernel.Enums;

namespace US.Web.Client.Services;

public sealed class UiTextService
{
    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Common.Region"] = "Region",
            ["Common.Language"] = "Language",
            ["Common.Location"] = "Location",
            ["Common.IssueType"] = "Issue type",
            ["Common.Status"] = "Status",
            ["Common.Urgency"] = "Urgency",
            ["Common.Submitted"] = "Submitted",
            ["Common.Refresh"] = "Refresh",
            ["Common.Refreshing"] = "Refreshing...",
            ["Common.Online"] = "Online",
            ["Common.Offline"] = "Offline",
            ["Common.Sync"] = "Sync",
            ["Common.Syncing"] = "Syncing...",
            ["Common.Pending"] = "pending",
            ["Common.Ok"] = "OK",
            ["Common.Error"] = "Something went wrong",
            ["Common.View"] = "View",
            ["Common.Edit"] = "Edit",
            ["Common.Delete"] = "Delete",
            ["Common.Actions"] = "Actions",
            ["Common.Cancel"] = "Cancel",
            ["Common.Close"] = "Close",
            ["Common.BackToReports"] = "Back to reports",
            ["Common.None"] = "None",
            ["Nav.Dashboard"] = "Dashboard",
            ["Nav.Reports"] = "Reports",
            ["Nav.Map"] = "Map",
            ["Nav.AllReports"] = "All reports",
            ["Nav.Submit"] = "Submit",
            ["Nav.Validate"] = "Validate",
            ["Auth.Reporter"] = "Reporter",
            ["Auth.Validator"] = "Validator",
            ["Auth.Admin"] = "Admin",
            ["Auth.ValidatorLogin"] = "Validator login",
            ["Auth.AdminLogin"] = "Admin login",
            ["Auth.Logout"] = "Logout",
            ["Auth.Login"] = "Login",
            ["Auth.RestrictedAccess"] = "Restricted access",
            ["Auth.LoginHint"] = "Validators and administrators can sign in here. Community reporters do not need an account.",
            ["Auth.Username"] = "Username",
            ["Auth.Password"] = "Password",
            ["Auth.SigningIn"] = "Signing in...",
            ["Auth.AccessDenied"] = "Access denied. Check your username and password.",
            ["Auth.LoginFailed"] = "Login failed. Confirm the API is running and try again.",
            ["Auth.DemoUsers"] = "Demo users",
            ["Submit.Eyebrow"] = "Community reporting",
            ["Submit.Title"] = "Submit a community accountability report",
            ["Submit.Lede"] = "Capture what happened, where it happened, and who is leading the response. AI will help structure the report, but human validators decide what moves forward.",
            ["Submit.LocationPlaceholder"] = "Village, town, landmark, or GPS hint",
            ["Submit.WhatHappened"] = "What happened?",
            ["Submit.DescriptionPlaceholder"] = "Describe the report in the community member's own words.",
            ["Submit.WomenLed"] = "Women-led",
            ["Submit.YouthLed"] = "Youth-led",
            ["Submit.Sensitive"] = "Sensitive/anonymize",
            ["Submit.Submit"] = "Submit report",
            ["Submit.UseUssd"] = "Use USSD",
            ["Submit.Submitting"] = "Submitting...",
            ["Submit.RegionContext"] = "Region context",
            ["Submit.LoadingRegions"] = "Loading region profiles...",
            ["Submit.RegionalBodies"] = "Regional bodies",
            ["Submit.EscalationPathways"] = "Escalation pathways",
            ["Submit.Submitted"] = "Submitted",
            ["Submit.Queued"] = "Report queued for human validation",
            ["Submit.SavedOffline"] = "No connection to the API right now. The report was saved locally and can be synced later.",
            ["Submit.SyncedAll"] = "Synced {0} pending report(s).",
            ["Submit.SyncedSome"] = "Synced {0} of {1}. {2} still pending.",
            ["Submit.SafetyTitle"] = "Human validation required",
            ["Submit.SafetyBody"] = "AI assistance may structure evidence, but community consent, validator review, and safety checks are required before escalation.",
            ["Submit.DescriptionRequired"] = "Describe what happened before submitting.",
            ["Submit.LocationRequired"] = "Add the community location before submitting.",
            ["Submit.IssueTypeRequired"] = "Select an issue type before submitting. Use the suggestion if it looks correct.",
            ["Submit.DescriptionTooShort"] = "Please provide at least 10 characters so validators have enough context.",
            ["Submit.DescriptionTooLong"] = "Please keep the report under 4,000 characters for this MVP.",
            ["Submit.SubmitFailed"] = "Submission failed. The report was saved locally and can be synced later.",
            ["Submit.Success"] = "Report submitted and queued for human validation.",
            ["Submit.SuccessTitle"] = "Report submitted",
            ["Submit.SuccessDetail"] = "Your report has been queued for human validation.",
            ["Submit.OfflineTitle"] = "Saved for sync",
            ["Submit.SyncTitle"] = "Sync complete",
            ["Submit.ValidationError"] = "Please fix the highlighted issue before submitting.",
            ["Submit.SuggestedIssue"] = "Suggested issue",
            ["Submit.Signals"] = "signals",
            ["Submit.UseSuggestion"] = "Use",
            ["Submit.IgnoreSuggestion"] = "Ignore",
            ["Ussd.Title"] = "USSD community intake",
            ["Ussd.Subtitle"] = "Feature-phone style submission through the real USSD-shaped API endpoint.",
            ["Ussd.InitialScreen"] = "Dial *384# and start session.",
            ["Ussd.Reply"] = "Reply",
            ["Ussd.Send"] = "Send",
            ["Ussd.StartSession"] = "Start session",
            ["Ussd.Reset"] = "Reset",
            ["Ussd.Close"] = "Close",
            ["Ussd.GatewayUnavailable"] = "USSD gateway unavailable. Confirm US.Api is running on http://localhost:5138, then start the session again.",
            ["Ussd.ReportQueued"] = "Report queued for human validation.",
            ["Ussd.FieldIntake"] = "Field intake",
            ["Ussd.SimulatorTitle"] = "USSD community intake simulator",
            ["Ussd.SimulatorLede"] = "A feature-phone style flow for communities without smartphones or stable internet. The simulator posts to a real USSD-shaped API endpoint.",
            ["Ussd.UseWebForm"] = "Use web form",
            ["Region.drc.Description"] = "Community accountability and reparative justice workflows for mining, displacement, and service-delivery commitments.",
            ["Region.drc.Pathways"] = "Local peace committee -> Provincial authority -> OSF partner review -> Regional body briefing",
            ["Region.sahel.Description"] = "Low-bandwidth civic evidence workflows for communities affected by insecurity, displacement, and governance exclusion.",
            ["Region.sahel.Pathways"] = "Community validator -> Civil society partner -> ECOWAS policy channel",
            ["Region.sudan.Description"] = "Anonymity-aware reporting for communities documenting displacement, local harms, and recovery needs.",
            ["Region.sudan.Pathways"] = "Trusted validator -> Humanitarian partner -> OSF legal or advocacy review",
            ["Region.mozambique.Description"] = "Localized reporting and accountability workflows for recovery, resource governance, and community resilience.",
            ["Region.mozambique.Pathways"] = "Local partner -> District authority -> SADC-aligned advocacy brief",
            ["Dashboard.Eyebrow"] = "Realtime dashboard",
            ["Dashboard.Title"] = "Community accountability metrics",
            ["Dashboard.Lede"] = "Live operational signals for report volume, validation pressure, urgency, follow-up, and approvals.",
            ["Dashboard.Live"] = "Live",
            ["Dashboard.Connecting"] = "Connecting",
            ["Dashboard.Total"] = "Total reports",
            ["Dashboard.PendingValidation"] = "Pending validation",
            ["Dashboard.HighCritical"] = "High/Critical urgency",
            ["Dashboard.FollowUp"] = "Needs follow-up",
            ["Dashboard.Approved"] = "Approved",
            ["Dashboard.EmptyTitle"] = "No reports yet",
            ["Dashboard.EmptyBody"] = "Submit a report to see the realtime feed update.",
            ["Map.Eyebrow"] = "Dual-zone intelligence",
            ["Map.Title"] = "Conflict and resilience map",
            ["Map.Lede"] = "Ubuntu Sentinel maps where accountability is failing and where community peace systems are working.",
            ["Map.ConflictZone"] = "Conflict zone",
            ["Map.ResilienceZone"] = "Resilience zone",
            ["Map.Evidence"] = "Evidence",
            ["Map.Signal"] = "Signal",
            ["Reports.Eyebrow"] = "Report operations",
            ["Reports.Title"] = "Community reports",
            ["Reports.Lede"] = "Browse submitted reports, inspect status, and open accountability briefs without crowding the metrics dashboard.",
            ["Reports.EmptyTitle"] = "No reports yet",
            ["Reports.EmptyBody"] = "Submit a report to populate the operational report list.",
            ["Reports.CreateNew"] = "Create new",
            ["Reports.DetailsTitle"] = "Report details",
            ["Reports.DetailsSubtitle"] = "Read-only report status, validation checks, and notes.",
            ["Reports.Validate"] = "Validate",
            ["Reports.SensitiveHidden"] = "Sensitive report. Details remain hidden in shared views until a validator confirms consent and reporter safety.",
            ["Reports.ViewPipeline"] = "View pipeline",
            ["Reports.GenerateBrief"] = "Generate accountability brief",
            ["Reports.GenerateDraftBrief"] = "Generate draft brief",
            ["Reports.EditPendingTitle"] = "Edit report",
            ["Reports.EditPendingBody"] = "Editing is available as a planned workflow after the MVP update endpoint is promoted.",
            ["Reports.DeleteSuccessTitle"] = "Report deleted",
            ["Reports.DeleteSuccess"] = "The report was removed from the operational list.",
            ["Reports.DeleteFailed"] = "The report could not be deleted. Please refresh and try again.",
            ["Reports.DeleteConfirmTitle"] = "Delete report?",
            ["Reports.DeleteConfirmBody"] = "This removes the report from the current MVP data store.",
            ["Validate.Eyebrow"] = "Human validation",
            ["Validate.Title"] = "Review community reports before escalation",
            ["Validate.Lede"] = "AI can structure and summarize evidence, but validators decide what is approved, rejected, or sent for follow-up.",
            ["Validate.Pending"] = "pending validation",
            ["Validate.WorkQueue"] = "in validation/follow-up",
            ["Validate.LoadingTitle"] = "Loading reports",
            ["Validate.LoadingBody"] = "Fetching the latest validation queue.",
            ["Validate.EmptyTitle"] = "No reports need review",
            ["Validate.EmptyBody"] = "New submissions and follow-up cases will appear here.",
            ["Validate.Notes"] = "Validator notes",
            ["Validate.NotesPlaceholder"] = "What should advocates or follow-up teams know?",
            ["Validate.NotesRequired"] = "Validator notes are required for every validation decision.",
            ["Validate.Checklist"] = "Validation checks",
            ["Validate.ConsentCheck"] = "Consent confirmed",
            ["Validate.LocationCheck"] = "Location confidence checked",
            ["Validate.EvidenceCheck"] = "Evidence quality checked",
            ["Validate.SafetyCheck"] = "Reporter safety checked",
            ["Validate.ApproveBlocked"] = "Complete all validation checks before approving.",
            ["Validate.Approve"] = "Approve",
            ["Validate.FollowUp"] = "Follow-up",
            ["Validate.Reject"] = "Reject",
            ["Validate.Marked"] = "Report {0} marked as {1}.",
            ["Validate.ActionCompleteTitle"] = "Validation updated",
            ["Validate.ActionCompleteBody"] = "The report status was updated and the dashboard has been notified.",
            ["Validate.ActionFailed"] = "The validation action could not be completed. Please try again.",
            ["Validate.SensitiveHandling"] = "Sensitive handling required",
            ["Validate.SensitiveDescription"] = "Sensitive report. Validator should confirm consent and safety before exposing full details. Internal description: {0}",
            ["Validate.SafetyTitle"] = "Validator responsibility",
            ["Validate.SafetyBody"] = "Approvals should confirm consent, location confidence, evidence quality, and reporter safety before any institutional escalation."
            ,
            ["Pipeline.PageTitle"] = "Agent Pipeline",
            ["Pipeline.Eyebrow"] = "Codex agentic pipeline",
            ["Pipeline.Title"] = "Community testimony to accountability intelligence",
            ["Pipeline.Lede"] = "The report is structured, compared against seeded commitments, checked for safety, and drafted into an accountability brief for human validation.",
            ["Pipeline.OpenBrief"] = "Open brief",
            ["Pipeline.RunningTitle"] = "Running pipeline",
            ["Pipeline.RunningBody"] = "Preparing the four-agent accountability workflow.",
            ["Pipeline.LoadFailed"] = "Could not load the agent pipeline.",
            ["Pipeline.ReportStatus"] = "Report status",
            ["Pipeline.Issue"] = "Issue",
            ["Pipeline.Confidence"] = "Confidence",
            ["Pipeline.PolicyMatch"] = "Policy match",
            ["Pipeline.Mode"] = "Pipeline mode",
            ["Pipeline.ModeOpenAI"] = "OpenAI-backed",
            ["Pipeline.ModeFallback"] = "Deterministic fallback",
            ["Pipeline.ApiKeyMissing"] = "OPENAI_API_KEY is not configured, so Ubuntu Sentinel is using deterministic fallback: real report data is still structured, matched against the seeded policy corpus, and shown with traceable reasoning, but live OpenAI agent judgement and richer narrative drafting are disabled.",
            ["Pipeline.OpenAiFailed"] = "OpenAI pipeline failed, so deterministic fallback was used. The result remains traceable against report data and policy sources, but live agent judgement should be retried before a final demo or escalation.",
            ["Pipeline.FallbackTitle"] = "Fallback mode active",
            ["Pipeline.IssueConflict"] = "Issue type conflict: reporter selected",
            ["Pipeline.IssueUsed"] = "pipeline used",
            ["Pipeline.Signals"] = "signals",
            ["Pipeline.ClauseComparison"] = "Real-source clause comparison",
            ["Pipeline.ComparedClaim"] = "Compared claim",
            ["Pipeline.Clause"] = "Clause",
            ["Pipeline.DocumentType"] = "Type",
            ["Pipeline.Source"] = "Source",
            ["Pipeline.Gap"] = "Detected gap",
            ["Pipeline.NoMatchTitle"] = "No confident clause match yet",
            ["Pipeline.NoMatchBody"] = "The pipeline did not find enough domain evidence to attach a specific real-source clause. A validator should request or upload the relevant policy, agreement, service rule, or public commitment before escalation.",
            ["Brief.PageTitle"] = "Accountability Brief",
            ["Brief.Eyebrow"] = "AI-assisted accountability",
            ["Brief.GeneratingTitle"] = "Generating brief",
            ["Brief.GeneratingBody"] = "Running the demo accountability pipeline.",
            ["Brief.LoadFailed"] = "Could not load the accountability brief.",
            ["Brief.ValidationGate"] = "Validation gate",
            ["Brief.Complete"] = "Complete",
            ["Brief.Draft"] = "Draft",
            ["Brief.HumanValidationGate"] = "Human validation gate",
            ["Brief.ReadyTitle"] = "Ready for escalation review",
            ["Brief.NotReadyTitle"] = "Not escalation-ready",
            ["Brief.SourceUsed"] = "Source used",
            ["Brief.ExportReady"] = "Export-ready brief",
            ["Brief.InternalDraft"] = "Internal draft brief",
            ["Brief.PrintPdf"] = "Download PDF brief",
            ["Brief.ExportJson"] = "Export JSON",
            ["Brief.ValidatedTitle"] = "Validation-backed accountability brief",
            ["Brief.DraftTitle"] = "Draft accountability brief",
            ["Brief.ValidatedLede"] = "This output has an approved report behind it, but still requires responsible partner review before escalation.",
            ["Brief.DraftLede"] = "This output is an internal draft. Human validation is required before escalation.",
            ["Brief.ValidatedSafetyTitle"] = "Validated report",
            ["Brief.DraftSafetyTitle"] = "Draft/unvalidated output",
            ["Brief.ValidatedSafetyBody"] = "The underlying report has passed human validation. Use this brief for responsible review, partner coordination, and escalation planning.",
            ["Brief.DraftSafetyBody"] = "This brief is generated assistance. It is not a legal finding, verified evidence, or authorization to escalate without human validation and community safety review.",
            ["Brief.ValidationComplete"] = "A human validator has confirmed consent, location confidence, evidence quality, and reporter safety.",
            ["Brief.ValidationPending"] = "Keep this as internal intelligence until the validator completes every required check and approves the report."
        },
        ["fr"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Common.Region"] = "Region",
            ["Common.Language"] = "Langue",
            ["Common.Location"] = "Lieu",
            ["Common.IssueType"] = "Type de probleme",
            ["Common.Status"] = "Statut",
            ["Common.Urgency"] = "Urgence",
            ["Common.Submitted"] = "Soumis",
            ["Common.Refresh"] = "Actualiser",
            ["Common.Refreshing"] = "Actualisation...",
            ["Common.Online"] = "En ligne",
            ["Common.Offline"] = "Hors ligne",
            ["Common.Sync"] = "Synchroniser",
            ["Common.Syncing"] = "Synchronisation...",
            ["Common.Pending"] = "en attente",
            ["Common.Ok"] = "OK",
            ["Common.Error"] = "Une erreur est survenue",
            ["Common.View"] = "Voir",
            ["Common.Edit"] = "Modifier",
            ["Common.Delete"] = "Supprimer",
            ["Common.Actions"] = "Actions",
            ["Common.Cancel"] = "Annuler",
            ["Common.Close"] = "Fermer",
            ["Common.BackToReports"] = "Retour aux rapports",
            ["Common.None"] = "Aucun",
            ["Nav.Dashboard"] = "Tableau de bord",
            ["Nav.Reports"] = "Rapports",
            ["Nav.Map"] = "Carte",
            ["Nav.AllReports"] = "Tous les rapports",
            ["Nav.Submit"] = "Soumettre",
            ["Nav.Validate"] = "Valider",
            ["Auth.Reporter"] = "Declarant",
            ["Auth.Validator"] = "Validateur",
            ["Auth.Admin"] = "Admin",
            ["Auth.ValidatorLogin"] = "Connexion validateur",
            ["Auth.AdminLogin"] = "Connexion admin",
            ["Auth.Logout"] = "Deconnexion",
            ["Auth.Login"] = "Connexion",
            ["Auth.RestrictedAccess"] = "Acces restreint",
            ["Auth.LoginHint"] = "Les validateurs et administrateurs peuvent se connecter ici. Les declarants communautaires n'ont pas besoin de compte.",
            ["Auth.Username"] = "Nom d'utilisateur",
            ["Auth.Password"] = "Mot de passe",
            ["Auth.SigningIn"] = "Connexion...",
            ["Auth.AccessDenied"] = "Acces refuse. Verifiez le nom d'utilisateur et le mot de passe.",
            ["Auth.LoginFailed"] = "La connexion a echoue. Confirmez que l'API fonctionne puis reessayez.",
            ["Auth.DemoUsers"] = "Utilisateurs demo",
            ["Submit.Eyebrow"] = "Signalement communautaire",
            ["Submit.Title"] = "Soumettre un rapport de responsabilite communautaire",
            ["Submit.Lede"] = "Documentez ce qui s'est passe, ou cela s'est passe et qui mene la reponse. L'IA aide a structurer le rapport, mais les validateurs humains decident de la suite.",
            ["Submit.LocationPlaceholder"] = "Village, ville, point de repere ou indication GPS",
            ["Submit.WhatHappened"] = "Que s'est-il passe ?",
            ["Submit.DescriptionPlaceholder"] = "Decrivez le rapport avec les mots de la communaute.",
            ["Submit.WomenLed"] = "Dirige par des femmes",
            ["Submit.YouthLed"] = "Dirige par des jeunes",
            ["Submit.Sensitive"] = "Sensible/anonymiser",
            ["Submit.Submit"] = "Soumettre le rapport",
            ["Submit.UseUssd"] = "Utiliser USSD",
            ["Submit.Submitting"] = "Soumission...",
            ["Submit.RegionContext"] = "Contexte regional",
            ["Submit.LoadingRegions"] = "Chargement des profils regionaux...",
            ["Submit.RegionalBodies"] = "Organismes regionaux",
            ["Submit.EscalationPathways"] = "Voies d'escalade",
            ["Submit.Submitted"] = "Soumis",
            ["Submit.Queued"] = "Rapport en attente de validation humaine",
            ["Submit.SavedOffline"] = "Pas de connexion a l'API pour le moment. Le rapport a ete enregistre localement et pourra etre synchronise plus tard.",
            ["Submit.SyncedAll"] = "{0} rapport(s) en attente synchronise(s).",
            ["Submit.SyncedSome"] = "{0} sur {1} synchronise(s). {2} reste(nt) en attente.",
            ["Submit.SafetyTitle"] = "Validation humaine requise",
            ["Submit.SafetyBody"] = "L'assistance IA peut structurer les preuves, mais le consentement communautaire, l'examen d'un validateur et les controles de securite sont requis avant toute escalade.",
            ["Submit.DescriptionRequired"] = "Decrivez ce qui s'est passe avant de soumettre.",
            ["Submit.LocationRequired"] = "Ajoutez le lieu communautaire avant de soumettre.",
            ["Submit.IssueTypeRequired"] = "Selectionnez un type de probleme avant de soumettre. Utilisez la suggestion si elle semble correcte.",
            ["Submit.DescriptionTooShort"] = "Veuillez fournir au moins 10 caracteres afin que les validateurs aient assez de contexte.",
            ["Submit.DescriptionTooLong"] = "Veuillez garder le rapport sous 4 000 caracteres pour ce MVP.",
            ["Submit.SubmitFailed"] = "La soumission a echoue. Le rapport a ete enregistre localement et pourra etre synchronise plus tard.",
            ["Submit.Success"] = "Rapport soumis et place en attente de validation humaine.",
            ["Submit.SuccessTitle"] = "Rapport soumis",
            ["Submit.SuccessDetail"] = "Votre rapport est en attente de validation humaine.",
            ["Submit.OfflineTitle"] = "Enregistre pour synchronisation",
            ["Submit.SyncTitle"] = "Synchronisation terminee",
            ["Submit.ValidationError"] = "Veuillez corriger le probleme indique avant de soumettre.",
            ["Submit.SuggestedIssue"] = "Type suggere",
            ["Submit.Signals"] = "signaux",
            ["Submit.UseSuggestion"] = "Utiliser",
            ["Submit.IgnoreSuggestion"] = "Ignorer",
            ["Ussd.Title"] = "Signalement communautaire USSD",
            ["Ussd.Subtitle"] = "Soumission type telephone simple via le vrai point d'API au format USSD.",
            ["Ussd.InitialScreen"] = "Composez *384# puis demarrez la session.",
            ["Ussd.Reply"] = "Reponse",
            ["Ussd.Send"] = "Envoyer",
            ["Ussd.StartSession"] = "Demarrer",
            ["Ussd.Reset"] = "Reinitialiser",
            ["Ussd.Close"] = "Fermer",
            ["Ussd.GatewayUnavailable"] = "Passerelle USSD indisponible. Confirmez que US.Api fonctionne sur http://localhost:5138, puis recommencez la session.",
            ["Ussd.ReportQueued"] = "Rapport mis en attente de validation humaine.",
            ["Ussd.FieldIntake"] = "Collecte terrain",
            ["Ussd.SimulatorTitle"] = "Simulateur USSD de signalement communautaire",
            ["Ussd.SimulatorLede"] = "Un flux type telephone simple pour les communautes sans smartphone ou connexion stable. Le simulateur appelle un vrai point d'API au format USSD.",
            ["Ussd.UseWebForm"] = "Utiliser le formulaire web",
            ["Region.drc.Description"] = "Flux de responsabilite communautaire et de justice reparatrice pour les engagements lies aux mines, aux deplacements et aux services.",
            ["Region.drc.Pathways"] = "Comite local de paix -> Autorite provinciale -> Revue par un partenaire OSF -> Note aux organismes regionaux",
            ["Region.sahel.Description"] = "Flux de preuves civiques a faible bande passante pour les communautes touchees par l'insecurite, le deplacement et l'exclusion de gouvernance.",
            ["Region.sahel.Pathways"] = "Validateur communautaire -> Partenaire de la societe civile -> Canal politique de la CEDEAO",
            ["Region.sudan.Description"] = "Signalement sensible a l'anonymat pour les communautes documentant les deplacements, les prejudices locaux et les besoins de retablissement.",
            ["Region.sudan.Pathways"] = "Validateur de confiance -> Partenaire humanitaire -> Revue juridique ou plaidoyer OSF",
            ["Region.mozambique.Description"] = "Flux localises de signalement et de responsabilite pour le retablissement, la gouvernance des ressources et la resilience communautaire.",
            ["Region.mozambique.Pathways"] = "Partenaire local -> Autorite de district -> Brief de plaidoyer aligne avec la SADC",
            ["Dashboard.Eyebrow"] = "Tableau de bord en temps reel",
            ["Dashboard.Title"] = "Indicateurs de responsabilite communautaire",
            ["Dashboard.Lede"] = "Signaux operationnels en direct sur le volume, la validation, l'urgence, le suivi et les approbations.",
            ["Dashboard.Live"] = "En direct",
            ["Dashboard.Connecting"] = "Connexion",
            ["Dashboard.Total"] = "Total des rapports",
            ["Dashboard.PendingValidation"] = "En attente de validation",
            ["Dashboard.HighCritical"] = "Urgence elevee/critique",
            ["Dashboard.FollowUp"] = "Suivi requis",
            ["Dashboard.Approved"] = "Approuves",
            ["Dashboard.EmptyTitle"] = "Aucun rapport pour le moment",
            ["Dashboard.EmptyBody"] = "Soumettez un rapport pour voir le flux se mettre a jour.",
            ["Map.Eyebrow"] = "Intelligence a deux zones",
            ["Map.Title"] = "Carte des conflits et de la resilience",
            ["Map.Lede"] = "Ubuntu Sentinel cartographie les lieux ou la responsabilite echoue et ceux ou les systemes communautaires de paix fonctionnent.",
            ["Map.ConflictZone"] = "Zone de conflit",
            ["Map.ResilienceZone"] = "Zone de resilience",
            ["Map.Evidence"] = "Preuve",
            ["Map.Signal"] = "Signal",
            ["Reports.Eyebrow"] = "Operations de rapport",
            ["Reports.Title"] = "Rapports communautaires",
            ["Reports.Lede"] = "Consultez les rapports soumis, inspectez les statuts et ouvrez les briefs sans encombrer le tableau de bord.",
            ["Reports.EmptyTitle"] = "Aucun rapport pour le moment",
            ["Reports.EmptyBody"] = "Soumettez un rapport pour remplir la liste operationnelle.",
            ["Reports.CreateNew"] = "Creer",
            ["Reports.DetailsTitle"] = "Details du rapport",
            ["Reports.DetailsSubtitle"] = "Lecture seule du statut, des controles de validation et des notes.",
            ["Reports.Validate"] = "Valider",
            ["Reports.SensitiveHidden"] = "Rapport sensible. Les details restent caches dans les vues partagees jusqu'a confirmation du consentement et de la securite du declarant.",
            ["Reports.ViewPipeline"] = "Voir le pipeline",
            ["Reports.GenerateBrief"] = "Generer le brief de responsabilite",
            ["Reports.GenerateDraftBrief"] = "Generer un brouillon",
            ["Reports.EditPendingTitle"] = "Modifier le rapport",
            ["Reports.EditPendingBody"] = "La modification sera disponible apres la promotion du point d'API de mise a jour.",
            ["Reports.DeleteSuccessTitle"] = "Rapport supprime",
            ["Reports.DeleteSuccess"] = "Le rapport a ete retire de la liste operationnelle.",
            ["Reports.DeleteFailed"] = "Le rapport n'a pas pu etre supprime. Veuillez actualiser puis reessayer.",
            ["Reports.DeleteConfirmTitle"] = "Supprimer le rapport ?",
            ["Reports.DeleteConfirmBody"] = "Cette action retire le rapport du stockage MVP actuel.",
            ["Validate.Eyebrow"] = "Validation humaine",
            ["Validate.Title"] = "Examiner les rapports avant escalation",
            ["Validate.Lede"] = "L'IA peut structurer et resumer les preuves, mais les validateurs decident ce qui est approuve, rejete ou renvoye pour suivi.",
            ["Validate.Pending"] = "en attente de validation",
            ["Validate.WorkQueue"] = "en validation/suivi",
            ["Validate.LoadingTitle"] = "Chargement des rapports",
            ["Validate.LoadingBody"] = "Recuperation de la file de validation.",
            ["Validate.EmptyTitle"] = "Aucun rapport a examiner",
            ["Validate.EmptyBody"] = "Les nouvelles soumissions et les cas de suivi apparaitront ici.",
            ["Validate.Notes"] = "Notes du validateur",
            ["Validate.NotesPlaceholder"] = "Que doivent savoir les defenseurs ou les equipes de suivi ?",
            ["Validate.NotesRequired"] = "Les notes du validateur sont requises pour chaque decision de validation.",
            ["Validate.Checklist"] = "Controles de validation",
            ["Validate.ConsentCheck"] = "Consentement confirme",
            ["Validate.LocationCheck"] = "Fiabilite du lieu verifiee",
            ["Validate.EvidenceCheck"] = "Qualite des preuves verifiee",
            ["Validate.SafetyCheck"] = "Securite du declarant verifiee",
            ["Validate.ApproveBlocked"] = "Completez tous les controles avant d'approuver.",
            ["Validate.Approve"] = "Approuver",
            ["Validate.FollowUp"] = "Suivi",
            ["Validate.Reject"] = "Rejeter",
            ["Validate.Marked"] = "Rapport {0} marque comme {1}.",
            ["Validate.ActionCompleteTitle"] = "Validation mise a jour",
            ["Validate.ActionCompleteBody"] = "Le statut du rapport a ete mis a jour et le tableau de bord a ete notifie.",
            ["Validate.ActionFailed"] = "L'action de validation n'a pas pu etre effectuee. Veuillez reessayer.",
            ["Validate.SensitiveHandling"] = "Traitement sensible requis",
            ["Validate.SensitiveDescription"] = "Rapport sensible. Le validateur doit confirmer le consentement et la securite avant d'exposer les details. Description interne : {0}",
            ["Validate.SafetyTitle"] = "Responsabilite du validateur",
            ["Validate.SafetyBody"] = "Les approbations doivent confirmer le consentement, la fiabilite du lieu, la qualite des preuves et la securite du declarant avant toute escalade institutionnelle."
            ,
            ["Pipeline.PageTitle"] = "Pipeline agentique",
            ["Pipeline.Eyebrow"] = "Pipeline agentique Codex",
            ["Pipeline.Title"] = "Du temoignage communautaire a l'intelligence de responsabilite",
            ["Pipeline.Lede"] = "Le rapport est structure, compare aux engagements sources, verifie pour la securite, puis transforme en brief de responsabilite pour validation humaine.",
            ["Pipeline.OpenBrief"] = "Ouvrir le brief",
            ["Pipeline.RunningTitle"] = "Pipeline en cours",
            ["Pipeline.RunningBody"] = "Preparation du workflow de responsabilite en quatre agents.",
            ["Pipeline.LoadFailed"] = "Impossible de charger le pipeline agentique.",
            ["Pipeline.ReportStatus"] = "Statut du rapport",
            ["Pipeline.Issue"] = "Probleme",
            ["Pipeline.Confidence"] = "Confiance",
            ["Pipeline.PolicyMatch"] = "Correspondance",
            ["Pipeline.Mode"] = "Mode du pipeline",
            ["Pipeline.ModeOpenAI"] = "Appuye par OpenAI",
            ["Pipeline.ModeFallback"] = "Secours deterministe",
            ["Pipeline.ApiKeyMissing"] = "OPENAI_API_KEY n'est pas configure, donc Ubuntu Sentinel utilise le mode deterministe de secours : les donnees du rapport sont encore structurees, comparees au corpus de politiques source et affichees avec un raisonnement tracable, mais le jugement agentique OpenAI et la redaction narrative enrichie sont desactives.",
            ["Pipeline.OpenAiFailed"] = "Le pipeline OpenAI a echoue, donc le mode deterministe de secours a ete utilise. Le resultat reste tracable avec les donnees du rapport et les sources politiques, mais le jugement agentique devrait etre relance avant une demo finale ou une escalation.",
            ["Pipeline.FallbackTitle"] = "Mode de secours actif",
            ["Pipeline.IssueConflict"] = "Conflit de type : le declarant a selectionne",
            ["Pipeline.IssueUsed"] = "le pipeline a utilise",
            ["Pipeline.Signals"] = "signaux",
            ["Pipeline.ClauseComparison"] = "Comparaison avec une clause source",
            ["Pipeline.ComparedClaim"] = "Signalement compare",
            ["Pipeline.Clause"] = "Clause",
            ["Pipeline.DocumentType"] = "Type",
            ["Pipeline.Source"] = "Source",
            ["Pipeline.Gap"] = "Ecart detecte",
            ["Pipeline.NoMatchTitle"] = "Aucune clause fiable trouvee",
            ["Pipeline.NoMatchBody"] = "Le pipeline n'a pas trouve assez d'indices pour rattacher une clause source specifique. Un validateur doit demander ou charger la politique, l'accord, la regle de service ou l'engagement public pertinent avant toute escalation.",
            ["Brief.PageTitle"] = "Brief de responsabilite",
            ["Brief.Eyebrow"] = "Responsabilite assistee par IA",
            ["Brief.GeneratingTitle"] = "Generation du brief",
            ["Brief.GeneratingBody"] = "Execution du pipeline de responsabilite de demonstration.",
            ["Brief.LoadFailed"] = "Impossible de charger le brief de responsabilite.",
            ["Brief.ValidationGate"] = "Gate de validation",
            ["Brief.Complete"] = "Complet",
            ["Brief.Draft"] = "Brouillon",
            ["Brief.HumanValidationGate"] = "Gate de validation humaine",
            ["Brief.ReadyTitle"] = "Pret pour revue d'escalade",
            ["Brief.NotReadyTitle"] = "Pas pret pour escalation",
            ["Brief.SourceUsed"] = "Source utilisee",
            ["Brief.ExportReady"] = "Brief pret a exporter",
            ["Brief.InternalDraft"] = "Brief interne brouillon",
            ["Brief.PrintPdf"] = "Telecharger le brief PDF",
            ["Brief.ExportJson"] = "Exporter JSON",
            ["Brief.ValidatedTitle"] = "Brief de responsabilite valide",
            ["Brief.DraftTitle"] = "Brief de responsabilite brouillon",
            ["Brief.ValidatedLede"] = "Ce resultat repose sur un rapport approuve, mais necessite encore une revue responsable par les partenaires avant escalation.",
            ["Brief.DraftLede"] = "Ce resultat est un brouillon interne. La validation humaine est requise avant escalation.",
            ["Brief.ValidatedSafetyTitle"] = "Rapport valide",
            ["Brief.DraftSafetyTitle"] = "Sortie brouillon/non validee",
            ["Brief.ValidatedSafetyBody"] = "Le rapport sous-jacent a passe la validation humaine. Utilisez ce brief pour une revue responsable, la coordination des partenaires et la planification de l'escalade.",
            ["Brief.DraftSafetyBody"] = "Ce brief est une assistance generee. Ce n'est ni une conclusion juridique, ni une preuve verifiee, ni une autorisation d'escalade sans validation humaine et revue de securite communautaire.",
            ["Brief.ValidationComplete"] = "Un validateur humain a confirme le consentement, la fiabilite du lieu, la qualite des preuves et la securite du declarant.",
            ["Brief.ValidationPending"] = "Conservez ceci comme intelligence interne jusqu'a ce que le validateur complete chaque controle requis et approuve le rapport."
        }
    };

    public string Text(string languageCode, string key)
    {
        var normalized = Normalize(languageCode);
        if (Translations.TryGetValue(normalized, out var language) && language.TryGetValue(key, out var translated))
        {
            return translated;
        }

        return Translations["en"].GetValueOrDefault(key, key);
    }

    public string Format(string languageCode, string key, params object[] args)
    {
        return string.Format(Text(languageCode, key), args);
    }

    public string IssueType(string languageCode, IssueType issueType)
    {
        if (Normalize(languageCode) == "fr")
        {
            return issueType switch
            {
                SharedKernel.Enums.IssueType.BrokenPromise => "Promesse non tenue",
                SharedKernel.Enums.IssueType.ResourceConflict => "Conflit de ressources",
                SharedKernel.Enums.IssueType.GovernanceFailure => "Defaillance de gouvernance",
                SharedKernel.Enums.IssueType.SecurityConcern => "Probleme de securite",
                SharedKernel.Enums.IssueType.ServiceGap => "Manque de service",
                SharedKernel.Enums.IssueType.EnvironmentalHarm => "Prejudice environnemental",
                SharedKernel.Enums.IssueType.MediationSuccess => "Mediation reussie",
                SharedKernel.Enums.IssueType.RecoveryNeed => "Besoin de retablissement",
                SharedKernel.Enums.IssueType.CommunityResilience => "Resilience communautaire",
                _ => "Autre"
            };
        }

        return issueType switch
        {
            SharedKernel.Enums.IssueType.BrokenPromise => "Broken promise",
            SharedKernel.Enums.IssueType.ResourceConflict => "Resource conflict",
            SharedKernel.Enums.IssueType.GovernanceFailure => "Governance failure",
            SharedKernel.Enums.IssueType.SecurityConcern => "Security concern",
            SharedKernel.Enums.IssueType.ServiceGap => "Service gap",
            SharedKernel.Enums.IssueType.EnvironmentalHarm => "Environmental harm",
            SharedKernel.Enums.IssueType.MediationSuccess => "Mediation success",
            SharedKernel.Enums.IssueType.RecoveryNeed => "Recovery need",
            SharedKernel.Enums.IssueType.CommunityResilience => "Community resilience",
            _ => "Other"
        };
    }

    public string Status(string languageCode, ReportStatus status)
    {
        if (Normalize(languageCode) == "fr")
        {
            return status switch
            {
                ReportStatus.Draft => "Brouillon",
                ReportStatus.QueuedOffline => "En attente hors ligne",
                ReportStatus.Submitted => "Soumis",
                ReportStatus.Processing => "En traitement",
                ReportStatus.PendingValidation => "En validation",
                ReportStatus.Approved => "Approuve",
                ReportStatus.NeedsFollowUp => "Suivi requis",
                ReportStatus.Rejected => "Rejete",
                _ => status.ToString()
            };
        }

        return status switch
        {
            ReportStatus.Draft => "Draft",
            ReportStatus.QueuedOffline => "Queued offline",
            ReportStatus.Submitted => "Submitted",
            ReportStatus.Processing => "Processing",
            ReportStatus.PendingValidation => "Pending validation",
            ReportStatus.Approved => "Approved",
            ReportStatus.NeedsFollowUp => "Needs follow-up",
            ReportStatus.Rejected => "Rejected",
            _ => status.ToString()
        };
    }

    public string Urgency(string languageCode, UrgencyLevel urgency)
    {
        if (Normalize(languageCode) == "fr")
        {
            return urgency switch
            {
                UrgencyLevel.Low => "Faible",
                UrgencyLevel.Medium => "Moyenne",
                UrgencyLevel.High => "Elevee",
                UrgencyLevel.Critical => "Critique",
                _ => urgency.ToString()
            };
        }

        return urgency switch
        {
            UrgencyLevel.Low => "Low",
            UrgencyLevel.Medium => "Medium",
            UrgencyLevel.High => "High",
            UrgencyLevel.Critical => "Critical",
            _ => urgency.ToString()
        };
    }

    private static string Normalize(string? languageCode)
    {
        return string.Equals(languageCode, "fr", StringComparison.OrdinalIgnoreCase) ? "fr" : "en";
    }
}
